constants:
  root_url: <%= ENV['OC_BASE_URL']%>

  cloudfront:
    domain: <%= ENV['OCW_CLOUDFRONT_DOMAIN'] %>

  basic_auth:
    username: <%= ENV['OCW_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['OCW_BASIC_AUTH_PASSWORD'] %>

  cms_api:
    open_timeout: 50
    read_timeout: 50

  cms_web:
    default_entity: 'uber_banner'

  ost_web:
    url: <%= ENV['OCW_OST_URL'] %>
    sha256_salt: <%= ENV['OCW_SHA256_SECRET_SALT']%>
