constants:
  root_url: <%= ENV['OC_BASE_URL']%>

  cloudfront:
    domain: <%= ENV['OCW_CLOUDFRONT_DOMAIN'] %>

  basic_auth:
    username: <%= ENV['OW_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['OW_BASIC_AUTH_PASSWORD'] %>

  cms_api:
    open_timeout: 50
    read_timeout: 50  
