meta:
    :1:
      :record_heading: news_list_title
      :fields:
        - news_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: news_list_title
        - news_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: news_list_description
        - news_list_image:
            :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: news_list_image
                :get_signed_url: api/content/get_signed_url
        - news_list_article_link:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Article Link
                :data_key_name: news_list_article_link
        - news_list_date:
            :meta_ui:
                :input_kind: generic-date-picker
                :input_label: Date
                :data_key_name: news_list_date
    :2:
          :record_heading: members_list_title
          :fields:
            - members_list_title:
                :meta_ui:
                    :input_kind: generic-select
                    :input_label: title
                    :data_key_name: members_list_title
                    :options: [option 1, option 2, option 3 ]
            - members_list_name:
                :meta_ui:
                    :input_kind: generic-text
                    :input_label: Name
                    :data_key_name: members_list_name
    :3:
          :record_heading: extended_team_url
          :fields:
            - extended_team_url:
                :meta_ui:
                    :input_kind: generic-link
                    :input_label: URL
                    :data_key_name: extended_team_url
            - extended_team_image:
                :meta_ui:
                    :input_kind: ost-input-file
                    :input_label: Image
                    :data_key_name: extended_team_image


