meta:
    :1:
      :record_heading: news_list_title
      :fields:
        - news_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: news_list_title
        - news_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: news_list_description
        - news_list_image:
            :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: news_list_image
        - news_list_article_link:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Article Link
                :data_key_name: news_list_article_link
        - news_list_date:
            :meta_ui:
                :input_kind: generic-date-picker
                :input_label: Date
                :data_key_name: news_list_date
    :2:
      :record_heading: members_list_title
      :fields:
        - members_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: members_list_title
        - members_list_name:
             :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: members_list_name
        - members_list_image:
             :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: members_list_image
        - members_list_linkedIn:
             :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn
                :data_key_name: members_list_linkedIn
        - members_list_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter
                :data_key_name: members_list_twitter
        - members_list_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium
                :data_key_name: members_list_medium
        - members_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: members_list_description


    :3:
      :record_heading: advisors_list_title
      :fields:
        - advisors_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: advisors_list_title
        - advisors_list_name:
             :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: advisors_list_name
        - advisors_list_image:
             :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: advisors_list_image
        - advisors_list_linkedIn:
             :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn
                :data_key_name: advisors_list_linkedIn
        - advisors_list_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter
                :data_key_name: advisors_list_twitter
        - advisors_list_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium
                :data_key_name: advisors_list_medium
        - advisors_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: advisors_list_description

    :4:
      :record_heading: partners_name
      :fields:
        - partners_name:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: partners_name
        - partners_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: partners_description
        - partners_founders:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Founders
                :data_key_name: partners_founders
        - partners_location:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Location
                :data_key_name: partners_location
        - partners_industry:
            :meta_ui:
                :input_kind: generic-select
                :input_label: Industry
                :data_key_name: partners_industry
                :options: [Social & Creative, Loyalty, DApps, Marketplace, Community, Sharing Economy]
        - partners_size:
            :meta_ui:
                :input_kind: generic-select
                :input_label: Size
                :data_key_name: partners_industry
        - partners_url:
            :meta_ui:
                :input_kind: generic-link
                :input_label: URL
                :data_key_name: partners_url
        - partners_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter URL
                :data_key_name: partners_twitter
        - partners_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium URL
                :data_key_name: partners_medium
        - partners_linkedin:
            :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn URL
                :data_key_name: partners_linkedin



    :5:
        :record_heading: careers_title
        :fields:
          - careers_title:
              :meta_ui:
                  :input_kind: generic-text
                  :input_label: Title
                  :data_key_name: careers_title
          - careers_description:
                :meta_ui:
                    :input_kind: generic-textarea
                    :input_label: Description
                    :data_key_name: careers_description

          - careers_url:
              :meta_ui:
                  :input_kind: generic-link
                  :input_label: Job Description Link
                  :data_key_name: careers_url

    :6:
        :record_heading: careers_title
        :fields:
          - careers_title:
              :meta_ui:
                  :input_kind: generic-text
                  :input_label: Title
                  :data_key_name: careers_title
          - careers_description:
                :meta_ui:
                    :input_kind: generic-textarea
                    :input_label: Description
                    :data_key_name: careers_description

          - careers_url:
              :meta_ui:
                  :input_kind: generic-link
                  :input_label: Job Description Link
                  :data_key_name: careers_url
