meta:
    :news_list:
        - news_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: news_list_title
        - news_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: news_list_description
        - news_list_image:
            :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: news_list_image
        - news_list_article_link:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Article Link
                :data_key_name: news_list_article_link
        - news_list_date:
            :meta_ui:
                :input_kind: generic-date-picker
                :input_label: Date
                :data_key_name: news_list_date
