meta:
    :news_list:
      :record_heading: news_list_title
      :fields:
        - news_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :tooltip_title: News title is required field. Length of this should be less than 130 characters and greater than 5 characters.
                :data_key_name: news_list_title
        - news_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :tooltip_title: News description is optional field. Length of this should be less than 500 characters and greater than 40 characters.
                :data_key_name: news_list_description
        - news_list_image:
            :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :tooltip_title: News image is required field. Allowed image size is 1KB - 100MB.
                :data_key_name: news_list_image
        - news_list_article_link:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Article Link
                :tooltip_title: News article url is optional field.
                :data_key_name: news_list_article_link
        - news_list_date:
            :meta_ui:
                :input_kind: generic-date-picker
                :input_label: News Published Date
                :data_key_name: news_list_date
                :tooltip_title: News date is required field.
        - news_list_video_embed:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Video Embed Url
                :data_key_name: news_list_video_embed
                :tooltip_title: News video url is optional field

    :members_list:
      :record_heading: members_list_title
      :fields:
        - members_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: members_list_title
                :tooltip_title: Title of team member is required field. Length of this should be less than 50 characters and greater than 2 characters.
        - members_list_name:
             :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: members_list_name
                :tooltip_title: Name of team member is required field. Length of this should be less than 40 characters and greater than 2 characters.
        - members_list_image:
             :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: members_list_image
                :tooltip_title: Image of team member is required field. Allowed image size is 1KB - 100MB.
        - members_list_linkedIn:
             :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn
                :data_key_name: members_list_linkedIn
                :tooltip_title: LinkedIn url of team member is optional field.
        - members_list_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter
                :data_key_name: members_list_twitter
                :tooltip_title: Twitter url of team member is optional field.
        - members_list_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium
                :data_key_name: members_list_medium
                :tooltip_title: Medium url of team member is optional field.
        - members_list_website:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Website
                :data_key_name: members_list_website
                :tooltip_title: Website url of team member is optional field.
        - members_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: members_list_description
                :tooltip_title: Member description is required field. Length of this should be less than 500 characters and greater than 35 characters.


    :advisors_list:
      :record_heading: advisors_list_title
      :fields:
        - advisors_list_title:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Title
                :data_key_name: advisors_list_title
                :tooltip_title: Title of advisor is required field. Length of this should be less than 30 characters and greater than 2 characters.
        - advisors_list_name:
             :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: advisors_list_name
                :tooltip_title: Name of advisor is required field. Length of this should be less than 40 characters and greater than 2 characters.
        - advisors_list_image:
             :meta_ui:
                :input_kind: ost-input-file
                :input_label: Image
                :data_key_name: advisors_list_image
                :tooltip_title: Image of advisor is required field. Allowed image size is 1KB - 100MB.
        - advisors_list_linkedIn:
             :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn
                :data_key_name: advisors_list_linkedIn
                :tooltip_title: LinkedIn url of advisor is optional field.
        - advisors_list_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter
                :data_key_name: advisors_list_twitter
                :tooltip_title: Twitter url of advisor is optional field.
        - advisors_list_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium
                :data_key_name: advisors_list_medium
                :tooltip_title: Medium url of advisor is optional field.
        - advisors_list_website:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Website
                :data_key_name: advisors_list_website
                :tooltip_title: Website url of advisor is optional field.
        - advisors_list_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: advisors_list_description
                :tooltip_title: Member description is required field. Length of this should be less than 550 characters and greater than 35 characters.

    :partners_list:
      :record_heading: partners_name
      :fields:
        - partners_name:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Name
                :data_key_name: partners_name
                :tooltip_title: Name of partner is required field. Length of this should be less than 50 characters and greater than 2 characters.
        - partners_description:
            :meta_ui:
                :input_kind: generic-textarea
                :input_label: Description
                :data_key_name: partners_description
                :tooltip_title: Description of partner is required field. Length of this should be less than 700 characters and greater than 20 characters.
        - partners_founders:
            :meta_ui:
                :input_kind: generic-tagsinput
                :input_label: Founders
                :data_key_name: partners_founders
                :tooltip_title: Founders of partner is optional field.
        - partners_location:
            :meta_ui:
                :input_kind: generic-text
                :input_label: Location
                :data_key_name: partners_location
                :tooltip_title: Location of partner is optional field.
        - partners_industry:
            :meta_ui:
                :input_kind: generic-multiselect
                :input_label: Industry
                :data_key_name: partners_industry[]
                :options:
                  - name: Social & Creative
                    value: social-creative
                  - name: Loyalty
                    value: loyalty
                  - name: DApps
                    value: dapps
                  - name: Marketplace
                    value: marketplace
                  - name: Community
                    value: community
                  - name: Sharing Economy
                    value: sharing-economy
                :tooltip_title: Partner industry is required field.
        - partners_size:
            :meta_ui:
                :input_kind: generic-select
                :input_label: Size
                :data_key_name: partners_size
                :options:
                  - name: Startup
                    value: start-up
                  - name: Million User Platform
                    value: large
                :tooltip_title: Partner size is required field.
        - partners_is_exited:
            :meta_ui:
                :input_kind: generic-radio-button
                :input_label: Has exited
                :data_key_name: partners_is_exited
                :tooltip_title: Has Partner exited?
        - partners_sprite_index:
            :meta_ui:
                :input_kind: generic-number
                :input_label: Sprite Index
                :data_key_name: partners_sprite_index
                :tooltip_title: Sprite index of partner logo
        - partners_url:
            :meta_ui:
                :input_kind: generic-link
                :input_label: URL
                :data_key_name: partners_url
                :tooltip_title: Partners url, optional field
        - partners_twitter:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Twitter URL
                :data_key_name: partners_twitter
                :tooltip_title: Partners twitter url, optional field
        - partners_medium:
            :meta_ui:
                :input_kind: generic-link
                :input_label: Medium URL
                :data_key_name: partners_medium
                :tooltip_title: Partners medium url, optional field
        - partners_linkedin:
            :meta_ui:
                :input_kind: generic-link
                :input_label: LinkedIn URL
                :data_key_name: partners_linkedin
                :tooltip_title: Partners LinkedIn url, optional field
        - partners_on_hover_bgcolor:
            :meta_ui:
                :input_kind: generic-color-picker
                :input_label: On Hover Background Color
                :data_key_name: partners_on_hover_bgcolor
                :tooltip_title: Partners on hover background color


    :berlin_career_list:
        :record_heading: careers_title
        :fields:
          - careers_title:
              :meta_ui:
                  :input_kind: generic-text
                  :input_label: Title
                  :data_key_name: careers_title
                  :tooltip_title: Career title, required field
          - careers_description:
                :meta_ui:
                    :input_kind: generic-textarea
                    :input_label: Description
                    :data_key_name: careers_description
                    :tooltip_title: Career description, required field
          - careers_url:
              :meta_ui:
                  :input_kind: generic-link
                  :input_label: Job Description Link
                  :data_key_name: careers_url
                  :tooltip_title: Career url, required field

    :pune_career_list:
        :record_heading: careers_title
        :fields:
          - careers_title:
              :meta_ui:
                  :input_kind: generic-text
                  :input_label: Title
                  :data_key_name: careers_title
                  :tooltip_title: Career title, required field

          - careers_description:
                :meta_ui:
                    :input_kind: generic-textarea
                    :input_label: Description
                    :data_key_name: careers_description
                    :tooltip_title: Career description, required field
          - careers_url:
              :meta_ui:
                  :input_kind: generic-link
                  :input_label: Job Description Link
                  :data_key_name: careers_url
                  :tooltip_title: Career url, required field
